modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Hugman76/MoreArrows/issues"
logoFile="logo.png"

[[mods]]
modId="more_arrows"
version="1.0"
displayName="MoreArrows"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/MoreArrows/1.14/update.json"
credits="https://ftb.gamepedia.com/MoreArrows/Credits"
authors="Hugman"
description='''
    WIP
'''

[[dependencies.more_arrows]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.more_arrows]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"